# Generated by Django 4.2.3 on 2023-12-03 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Reservatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservatorio_cadastrado', models.CharField(max_length=200)),
                ('litro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Numero_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('cloro', models.FloatField()),
                ('ph', models.FloatField()),
                ('fluor', models.FloatField()),
                ('turbidez', models.FloatField()),
                ('relatorio', models.TextField()),
                ('reservatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.cadastro_reservatorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organiza_tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agora', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_selecionada', models.DateTimeField()),
                ('lembrete', models.TextField()),
                ('concluido', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Controle_Operacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('pre_cloro', models.FloatField()),
                ('cloro_esstacao', models.FloatField()),
                ('fluor', models.FloatField()),
                ('turbidez_estacao', models.FloatField()),
                ('relatorio', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anotacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('nota', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
