# Generated by Django 4.2.3 on 2023-11-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_numero_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numero_media',
            name='n',
            field=models.IntegerField(),
        ),
    ]
