# Generated by Django 4.2.11 on 2024-03-15 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_informacoes_analises_basicas_interna_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anotacoes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='numero_media',
            options={'verbose_name_plural': 'Para fazer média no app laboratorio'},
        ),
        migrations.AlterModelOptions(
            name='reservatorio',
            options={'verbose_name': 'Reservatório', 'verbose_name_plural': 'Reservatório'},
        ),
    ]
