# Generated by Django 4.2.10 on 2024-02-15 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_informacoes_analises_basicas_interna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastar_ptrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Obejeto cadastrado',
                'verbose_name_plural': 'Objetos cadastrados',
            },
        ),
    ]
