# Generated by Django 4.2.3 on 2023-11-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_alter_numero_media_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fluor_diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluor', models.FloatField()),
                ('relatorio', models.CharField(max_length=200)),
            ],
        ),
    ]
