# Generated by Django 4.2.3 on 2023-11-23 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratorio', '0005_fluor_diario_data_fluor_diario_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle_Operacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('pre_cloro', models.FloatField()),
                ('cloro_esstacao', models.FloatField()),
                ('turbidez_estacao', models.FloatField()),
                ('relatorio', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
