# Generated by Django 4.2.3 on 2023-11-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_controle_operacional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fluor_diario',
        ),
    ]
