# Generated by Django 4.2.3 on 2023-11-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_delete_fluor_diario'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle_operacional',
            name='fluor',
            field=models.FloatField(default=0.99),
            preserve_default=False,
        ),
    ]
