# Generated by Django 4.2.3 on 2023-11-26 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratorio', '0008_controle_operacional_fluor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Reservatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservatorio_cadastrado', models.CharField(max_length=200)),
                ('litro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('cloro', models.FloatField()),
                ('ph', models.FloatField()),
                ('fluor', models.FloatField()),
                ('turbidez', models.FloatField()),
                ('relatorio', models.TextField()),
                ('reservatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.cadastro_reservatorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
