# Generated by Django 4.2.3 on 2023-11-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0010_anotacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anotacoes',
            old_name='texto',
            new_name='nota',
        ),
    ]
