# Generated by Django 4.2.3 on 2023-11-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0011_rename_texto_anotacoes_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacoes',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
