# Generated by Django 4.2.3 on 2023-07-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=250)),
                ('nome', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=50)),
                ('boolean', models.BooleanField(default=False)),
            ],
        ),
    ]
