# Generated by Django 4.2.3 on 2023-12-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='aviso_images')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade_estado', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reclame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('nome', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=50)),
                ('email_ou_tel', models.CharField(max_length=30)),
                ('boolean', models.BooleanField(default=False)),
                ('resposta', models.CharField(max_length=300)),
            ],
        ),
    ]
