# Generated by Django 4.2.11 on 2024-03-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_inicial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={'verbose_name': 'Aviso no site', 'verbose_name_plural': 'Aviso no site'},
        ),
    ]
