# Generated by Django 4.2.3 on 2023-07-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_inicial', '0002_reclame_resposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='aviso_images')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
            ],
        ),
    ]
