# Generated by Django 4.2.3 on 2023-07-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_inicial', '0003_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='divulgar',
            field=models.BooleanField(default=False),
        ),
    ]
