# Generated by Django 4.2.3 on 2023-07-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_inicial', '0004_aviso_divulgar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='divulgar',
        ),
        migrations.AlterField(
            model_name='reclame',
            name='mensagem',
            field=models.TextField(),
        ),
    ]
