# Generated by Django 4.2.3 on 2023-07-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_inicial', '0005_remove_aviso_divulgar_alter_reclame_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclame',
            name='email_ou_tel',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
