# Generated by Django 4.2.3 on 2023-12-03 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque_Cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_quilo', models.IntegerField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.CharField(max_length=30)),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OperadoresAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluor_min', models.FloatField()),
                ('fluor_ideal', models.FloatField()),
                ('fluor_max', models.FloatField()),
                ('cloro_min', models.FloatField()),
                ('cloro_ideal', models.FloatField()),
                ('cloro_max', models.FloatField()),
                ('cor_min', models.FloatField()),
                ('cor_ideal', models.FloatField()),
                ('cor_max', models.FloatField()),
                ('ph_min', models.FloatField()),
                ('ph_ideal', models.FloatField()),
                ('ph_max', models.FloatField()),
                ('turbidez_min', models.FloatField()),
                ('turbidez_ideal', models.FloatField()),
                ('turbidez_max', models.FloatField()),
                ('parametro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabela_estoque_cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_final', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SaidaCaminhaPipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('relatorio', models.TextField()),
                ('placa', models.CharField(max_length=10)),
                ('destino', models.CharField(max_length=50)),
                ('motorista', models.CharField(max_length=60)),
                ('quantidade', models.FloatField()),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizado', models.BooleanField(default=False)),
                ('operador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hidrometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('hidrometro_150', models.FloatField()),
                ('hidrometro_200', models.FloatField()),
                ('hidrometro_poco', models.FloatField()),
                ('relatorio', models.TextField()),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cal_Quantidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=20)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('relatorio', models.TextField()),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Analise_Agua_tratada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloro', models.FloatField()),
                ('ph', models.FloatField()),
                ('fluor', models.FloatField()),
                ('cor', models.FloatField()),
                ('turbidez', models.FloatField()),
                ('relatorio', models.TextField()),
                ('data_analise_agua', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Analise_Agua_bruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decantada_ph', models.FloatField()),
                ('decantada_cor', models.FloatField()),
                ('decantada_turbidez', models.FloatField()),
                ('bruta_ph', models.FloatField()),
                ('bruta_cor', models.FloatField()),
                ('bruta_turbidez', models.FloatField()),
                ('relatorio', models.TextField()),
                ('qeta', models.FloatField()),
                ('qcal', models.FloatField()),
                ('qpac', models.FloatField()),
                ('data_analise_agua', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
