# Generated by Django 4.2.11 on 2024-03-15 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cal_quantidade',
            options={'verbose_name': 'Sacos  de cal usada pelo operador', 'verbose_name_plural': 'Sacos  de cal usada pelo operador'},
        ),
    ]
