# Generated by Django 4.2.11 on 2024-03-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_cal_quantidade_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'verbose_name': 'chat dos operadores', 'verbose_name_plural': 'chat dos operadores'},
        ),
    ]
