# Generated by Django 4.2.3 on 2023-07-25 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataforma', '0004_alter_analise_agua_tratada_data_analise_agua'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise_Agua_bruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decantada_ph', models.FloatField()),
                ('decantada_cor', models.FloatField()),
                ('decantada_turbidez', models.FloatField()),
                ('bruta_ph', models.FloatField()),
                ('bruta_cor', models.FloatField()),
                ('bruta_turbidez', models.FloatField()),
                ('relatorio', models.TextField()),
                ('qeta', models.FloatField()),
                ('qcal', models.FloatField()),
                ('qpac', models.FloatField()),
                ('data_analise_agua', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
