# Generated by Django 4.2.3 on 2023-07-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_analise_agua_bruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadoreAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviso', models.TextField()),
            ],
        ),
    ]
