# Generated by Django 4.2.3 on 2023-07-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_operadoreaviso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperadoreAviso',
            new_name='OperadoresAviso',
        ),
    ]
