# Generated by Django 4.2.3 on 2023-07-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_rename_operadoreaviso_operadoresaviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operadoresaviso',
            name='aviso',
            field=models.TextField(default='Tenha um bom serviço'),
        ),
    ]
