# Generated by Django 4.2.3 on 2023-07-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_alter_operadoresaviso_aviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operadoresaviso',
            name='aviso',
            field=models.TextField(),
        ),
    ]
