# Generated by Django 4.2.3 on 2023-07-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_alter_operadoresaviso_aviso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluor_min', models.FloatField()),
                ('fluor_ideal', models.FloatField()),
                ('fluor_max', models.FloatField()),
                ('cloro_min', models.FloatField()),
                ('cloro_ideal', models.FloatField()),
                ('cloro_max', models.FloatField()),
                ('cor_min', models.FloatField()),
                ('cor_ideal', models.FloatField()),
                ('cor_max', models.FloatField()),
                ('ph_min', models.FloatField()),
                ('ph_ideal', models.FloatField()),
                ('ph', models.FloatField()),
                ('parametro', models.TextField()),
            ],
        ),
    ]
