# Generated by Django 4.2.3 on 2023-07-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_parametro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametro',
            old_name='ph',
            new_name='ph_max',
        ),
    ]
