# Generated by Django 4.2.3 on 2023-07-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0011_rename_ph_parametro_ph_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='turbidez_ideal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parametro',
            name='turbidez_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parametro',
            name='turbidez_min',
            field=models.FloatField(default=0),
        ),
    ]
