# Generated by Django 4.2.3 on 2023-07-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_parametro_turbidez_ideal_parametro_turbidez_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='turbidez_ideal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='turbidez_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='turbidez_min',
            field=models.FloatField(),
        ),
    ]
