# Generated by Django 4.2.3 on 2023-07-29 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_cal_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque_Cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_unidade', models.IntegerField()),
                ('cal_quilo', models.IntegerField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
