# Generated by Django 4.2.3 on 2023-07-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_estoque_cal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque_cal',
            old_name='data',
            new_name='data_hora_formatada',
        ),
    ]
