# Generated by Django 4.2.3 on 2023-07-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0016_rename_data_estoque_cal_data_hora_formatada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque_cal',
            old_name='data_hora_formatada',
            new_name='data',
        ),
    ]
