# Generated by Django 4.2.3 on 2023-07-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0017_rename_data_hora_formatada_estoque_cal_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque_cal',
            name='cal_unidade',
        ),
    ]
