# Generated by Django 4.2.3 on 2023-07-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0018_remove_estoque_cal_cal_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela_estoque_cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_final', models.IntegerField()),
            ],
        ),
    ]
