# Generated by Django 4.2.3 on 2023-07-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0020_alter_tabela_estoque_cal_resultado_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cal_quantidade',
            name='relatorio',
        ),
    ]
