# Generated by Django 4.2.3 on 2023-07-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0021_remove_cal_quantidade_relatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cal_quantidade',
            name='relatorio',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
