# Generated by Django 4.2.3 on 2023-07-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0022_cal_quantidade_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal_quantidade',
            name='quantidade',
            field=models.TextField(),
        ),
    ]
