# Generated by Django 4.2.3 on 2023-07-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0023_alter_cal_quantidade_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal_quantidade',
            name='quantidade',
            field=models.CharField(max_length=20),
        ),
    ]
