# Generated by Django 4.2.3 on 2023-07-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0024_alter_cal_quantidade_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cal_quantidade',
            old_name='usuario',
            new_name='operador',
        ),
    ]
