# Generated by Django 4.2.3 on 2023-08-01 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataforma', '0025_rename_usuario_cal_quantidade_operador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hidrometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('hidrometro_150', models.FloatField()),
                ('hidrometro_200', models.FloatField()),
                ('hidrometro_poco', models.FloatField()),
                ('relatorio', models.TextField()),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
