# Generated by Django 4.2.3 on 2023-08-02 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataforma', '0026_hidrometro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaCaminhaPipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('relatorio', models.TextField()),
                ('placa', models.CharField(max_length=10)),
                ('destino', models.CharField(max_length=50)),
                ('motorista', models.CharField(max_length=60)),
                ('quantidade', models.FloatField()),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
