# Generated by Django 4.2.3 on 2023-10-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0028_mensagem_mural'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mural',
        ),
    ]
