# Generated by Django 4.2.3 on 2023-10-14 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataforma', '0031_alter_laboratorio_operador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='operador',
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='usuarios_autorizados',
            field=models.ManyToManyField(related_name='laboratorios_autorizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
