# Generated by Django 4.2.3 on 2023-11-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0033_remove_laboratorio_usuarios_autorizados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise_agua_tratada',
            name='fluor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
