# Generated by Django 4.2.3 on 2023-07-12 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etamidia',
            name='data_hora_criacao',
        ),
        migrations.AddField(
            model_name='etamidia',
            name='data_criacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
