# Generated by Django 4.2.11 on 2024-03-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etamidia',
            options={'verbose_name_plural': "Mensagem do SITE: 'Adicione titulo/foto/mensagem'"},
        ),
    ]
