# Generated by Django 4.2.11 on 2024-03-15 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eta', '0002_alter_etamidia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etamidia',
            options={'verbose_name_plural': 'Conheça a ETA'},
        ),
    ]
